name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      #RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.5.1'

#      - name: Install Dependencies
#        run: |
#          install.packages(c("shiny", "ggplot2", "dplyr", "rsconnect"))
#        shell: Rscript {0}
#
#      - name: Install Package Dependencies
#        run: |
#          install.packages(c("devtools", "testthat", "knitr", "rmarkdown"))
#        shell: Rscript {0}

      - name: Install the LearnStatsVis Package
        run: |
          install.packages(c("devtools","rsconnect"))
          # must use devtools to install from GitHub, otherwise errors
          # occur when deploying to shinyapps.io
          devtools::install_github("fortune9/Learn-statistics-by-visualization")
        shell: Rscript {0}

      - name: Configure rsconnect for shinyapps.io
        run: |
          rsconnect::setAccountInfo(name = '${{ secrets.SHINYAPPS_ACCOUNT_NAME }}', token = '${{ secrets.SHINYAPPS_TOKEN }}', secret = '${{ secrets.SHINYAPPS_SECRET }}')
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        run: |
          # Deploy the actual app from the shiny directory
          rsconnect::deployApp('shiny/', forceUpdate = TRUE, appName = '${{ vars.SHINYAPPS_APP_NAME }}', account = '${{ secrets.SHINYAPPS_ACCOUNT_NAME }}')
        shell: Rscript {0}
